// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0aPT6y0tQ-WPS2NqFg-WDxO4sQB6STJo',
    appId: '1:875965949091:web:144be39e63f05736600b16',
    messagingSenderId: '875965949091',
    projectId: 'vdoc-app',
    authDomain: 'vdoc-app.firebaseapp.com',
    storageBucket: 'vdoc-app.appspot.com',
    measurementId: 'G-30M3LWWT8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcW56ngPAt94GF70eecV306UBaWrGNNmc',
    appId: '1:875965949091:android:e5a8c937795a86d1600b16',
    messagingSenderId: '875965949091',
    projectId: 'vdoc-app',
    storageBucket: 'vdoc-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRA-z66WjK4R_CobHdtoWRgsyJJwtXhrU',
    appId: '1:875965949091:ios:e3261400783696f5600b16',
    messagingSenderId: '875965949091',
    projectId: 'vdoc-app',
    storageBucket: 'vdoc-app.appspot.com',
    iosBundleId: 'com.example.recipeHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0aPT6y0tQ-WPS2NqFg-WDxO4sQB6STJo',
    appId: '1:875965949091:web:0e113961a49a2258600b16',
    messagingSenderId: '875965949091',
    projectId: 'vdoc-app',
    authDomain: 'vdoc-app.firebaseapp.com',
    storageBucket: 'vdoc-app.appspot.com',
    measurementId: 'G-8ZDVMQ0QDH',
  );
}
